### ISSUE TITLE
Allow setting custom base url for OpenAI compatible endpoints

### ISSUE THREAD

**Issue by kagevazquez** [Royal-lobster/Syncia#61]
openai api support

https://lmstudio.ai/docs/local-server

r/LocalLLaMA

**Comment by Royal-lobster** [comment]
@kagevazquez Currently syncia already have https://ollama.com/ integration 

![CleanShot 2024-04-14 at 11 48 30](https://github.com/Royal-lobster/Syncia/assets/52039218/8744b7da-d301-4974-81aa-c3f6b44df2d8)

You can probably use this in mean time

**Comment by hdnh2006** [comment]
This is cool @Royal-lobster, but sometimes the model is not deployed locally.

It would be fantastic to provide a way to change the base_url. This should not be too complicated because I saw you use langchain, so this is just a single parameter called exactly like this: `base_url`. I can help you with how to list the models or any other question you have since I work daily with these APIs, but I don't know anything about Javascript. However, any other questions about structures or anything else, I would be more than happy to help you.

In any case, here you have the URL of my service (beta version) where you can use several LLMs for free: chat.privategpt.es.

Please let me know if you need anything else.

**Comment by Royal-lobster** [comment]
> # Note: text improved using Syncia
> This is cool @Royal-lobster, but sometimes the model is not deployed locally.
> 
> It would be fantastic to provide a way to change the base_url. This should not be too complicated because I saw you use langchain, so this is just a single parameter called exactly like this: `base_url`. I can help you with how to list the models or any other question you have since I work daily with these APIs, but I don't know anything about Javascript. However, any other questions about structures or anything else, I would be more than happy to help you.
> 
> In any case, here you have the URL of my service (beta version) where you can use several LLMs for free: chat.privategpt.es.
> 
> Please let me know if you need anything else.


This pr should add this support for custom base url ! https://github.com/Royal-lobster/Syncia/pull/80

**Comment by hdnh2006** [comment]
@Royal-lobster thank you so much for this quick support!! I'll try it as soon as I can
