### ISSUE TITLE
OpenAI API Key not recognized?

### ISSUE THREAD

**Issue by ioVideoMaker** [Royal-lobster/Syncia#76]
Hello everyone!
I'd like to use Syncia, but when I insert my secret API key I get a note to use a key which format is supported.

any idea why?
thanks!!

Marco

**Comment by Royal-lobster** [comment]
Hi !

The api key would be like this: sk-proj-________-________-________-________-________-________-________-________

make sure to give it all permissions, currently it fetches the list of models to verify if the key is valid or not, if we only give permission to completions it would not work

**Comment by ioVideoMaker** [comment]
Hello there! thanks for answering me!

I get a bunch of errors which I'm not knowledgeable enough to investigate,
could you please help?
NOTE: I correctly copy the API key from https://platform.openai.com/api-keys
NOTE: I have a paid account for chatGPT, so quota shouldn't be an issue

here's the screenshot

[image: image.png]


thank you!
Have a great day!


Marco

Il giorno mar 3 set 2024 alle ore 07:14 Srujan Gurram <
***@***.***> ha scritto:

**Comment by Royal-lobster** [comment]
For sure ! Hmm the image you've sent is broken, can you send it again ?

**Comment by Royal-lobster** [comment]
I believe your issue should be fixed with this: https://github.com/Royal-lobster/Syncia/pull/90

currently the update is in review from google webstore team, but may see it working in version 1.5.2

https://chromewebstore.google.com/detail/syncia-power-of-chatgpt-o/bhdfllifdfodbkihgmahlfmddlmfdjak?authuser=0&hl=en-GB

feel free to reopen this issue if its still not working
