### ISSUE TITLE
Still asking for OpenAP key while using local ollama

### ISSUE THREAD

**Issue by anhkind** [Royal-lobster/Syncia#77]
While using Chrome extensions, after I select the text and choose the action `Summarize`, the sidebar will just display just find with the results from Llama3.1 (Ollama). But if I type some more messages under the `Type your messages here ...`  textbox on the sidebar, I got this message
```
401 Incorrect API key provided: sk. You can find your API key at https://platform.openai.com/account/api-keys.
```
Please help fix it. Thanks

**Comment by Royal-lobster** [comment]
This should be fixed with https://github.com/Royal-lobster/Syncia/pull/90

currently the release is in review with chrome webstore team, once its done, you should be able to make it work. 

Also note that we now removed support for direct ollama, rather i believe you can launch openai compatible endpoint from ollama and use that endpoint in settings
